version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - '1433:1433'
    environment:
      # Username is 'SA'
      SA_PASSWORD: 'Prisma1234'
      ACCEPT_EULA: 'Y'
    volumes:
      - sqlserver:/var/opt/mssql
volumes:
  sqlserver:
